name: Deploy to ECR

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  biuld:
    name: Build image
    runs_on: ubuntu-latest

    steps:
     - name: Check out the repo
       uses: actions/checkout@v3

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v2
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1

     - name: Build, tag, and push image to Amazon ECR
       env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: exchange
        IMAGE_TAG: exchange_fasapi_image
       run: |
        docker-compose up -d
        docker-compose push

